
server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://rm-bp1tvrl98e40i934xjo.mysql.rds.aliyuncs.com:3306/room_store?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8
    password: Ab123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



  jpa:
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    database: 2

mybatis:
  type-aliases-package: cn.gson.room_store.model.pojos
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true

